name: delete event

on: delete

jobs:
  run:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v2
      - run: echo "delete event ${{ github.event.ref }}"
